# Treinamento

### Carregando Arquivo de Treinamento (.csv)

In [4]:
import pandas as pd
# Carregando dados do arquivo CSV
url = 'https://raw.githubusercontent.com/Kendy619/Classificador-KNN/main/diabetes.csv'
base_Treinamento = pd.read_csv(url,sep=',', encoding = 'latin1').values
print("--------------------------------------------------------")
print("Dados dos Pacientes - TREINAMENTO - Dimensão ",base_Treinamento)
print("--------------------------------------------------------")
print(base_Treinamento[:,:])
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Treinamento[:, :8])

print("----------------------------")
print("Classificação Supervisionada")
print("----------------------------")
print(base_Treinamento[:, 8])

--------------------------------------------------------
Dados dos Pacientes - TREINAMENTO - Dimensão  [[  6.    148.     72.    ...   0.627  50.      1.   ]
 [  1.     85.     66.    ...   0.351  31.      0.   ]
 [  8.    183.     64.    ...   0.672  32.      1.   ]
 ...
 [ 12.    100.     84.    ...   0.488  46.      0.   ]
 [  1.    147.     94.    ...   0.358  27.      1.   ]
 [  1.     81.     74.    ...   1.096  32.      0.   ]]
--------------------------------------------------------
[[  6.    148.     72.    ...   0.627  50.      1.   ]
 [  1.     85.     66.    ...   0.351  31.      0.   ]
 [  8.    183.     64.    ...   0.672  32.      1.   ]
 ...
 [ 12.    100.     84.    ...   0.488  46.      0.   ]
 [  1.    147.     94.    ...   0.358  27.      1.   ]
 [  1.     81.     74.    ...   1.096  32.      0.   ]]
---------------------------------
Atributos de Entrada
---------------------------------
[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.  

### Pré-processamento de Dados

In [6]:
import numpy as np 
from sklearn import preprocessing

# Binarizador de rótulo
min_max = preprocessing.MinMaxScaler()
atributos_normalizados = min_max.fit_transform(base_Treinamento[:,:8])


print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
print(atributos_normalizados)

print("----------------------------------------")
print("Classificação Supervisionada - Numéricos")
print("----------------------------------------")
diagnostico_normalizados = base_Treinamento[:,8]
print(diagnostico_normalizados)

--------------------------------
Atributos de Entrada - Numéricos
--------------------------------
[[0.35294118 0.74371859 0.59016393 ... 0.50074516 0.23441503 0.48333333]
 [0.05882353 0.42713568 0.54098361 ... 0.39642325 0.11656704 0.16666667]
 [0.47058824 0.91959799 0.52459016 ... 0.34724292 0.25362938 0.18333333]
 ...
 [0.70588235 0.50251256 0.68852459 ... 0.44709389 0.17506405 0.41666667]
 [0.05882353 0.73869347 0.7704918  ... 0.73472429 0.11955594 0.1       ]
 [0.05882353 0.40703518 0.60655738 ... 0.6900149  0.43467122 0.18333333]]
----------------------------------------
Classificação Supervisionada - Numéricos
----------------------------------------
[1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1.
 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0.
 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1.

### Treinamento do KNN (K-Nearest Neighbor)

In [8]:
from sklearn.neighbors import KNeighborsClassifier
# Treinamento do Knn a partir dos atributos de entrada e classificações com K=3
modelo = KNeighborsClassifier(n_neighbors=1)
modelo.fit(atributos_normalizados, diagnostico_normalizados)

# Acurácia do modelo, que é : 1 - (predições erradas / total de predições)
# Acurácia do modelo: indica uma performance geral do modelo. 
# Dentre todas as classificações, quantas o modelo classificou corretamente;
# (VP+VN)/N
print('Acurácia: %.4f' % modelo.score(atributos_normalizados, diagnostico_normalizados))

Acurácia: 1.0000


### ----------------------------------------------------------------------------

# Validação do Aprendizado 

### Predição Simples

In [10]:
Luiz = [[9,170,74,31,0,44,0.403,43]]
print("Luiz", modelo.predict(Luiz))
Laura = [[2,88,58,26,16,28.4,0.766,22]]
print("Laura", modelo.predict(Laura))

Luiz [1.]
Laura [1.]


### Predição a partir de base de dados (.csv)

In [11]:
import pandas as pd
# Carregando dados do arquivo CSV
url = 'https://raw.githubusercontent.com/Kendy619/Classificador-KNN/main/base_testes.csv'
base_Testes = pd.read_csv(url,sep=',', encoding = 'latin1').values
print("----------------------------")
print("Dados dos Pacientes - TESTES")
print("----------------------------")
print(base_Testes)
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Testes[:, 0:8])

----------------------------
Dados dos Pacientes - TESTES
----------------------------
[[3.000e+00 1.870e+02 7.000e+01 2.200e+01 2.000e+02 3.640e+01 4.080e-01
  3.600e+01 1.000e+00]
 [6.000e+00 1.620e+02 6.200e+01 0.000e+00 0.000e+00 2.430e+01 1.780e-01
  5.000e+01 1.000e+00]
 [4.000e+00 1.360e+02 7.000e+01 0.000e+00 0.000e+00 3.120e+01 1.182e+00
  2.200e+01 1.000e+00]
 [1.000e+00 1.210e+02 7.800e+01 3.900e+01 7.400e+01 3.900e+01 2.610e-01
  2.800e+01 0.000e+00]
 [3.000e+00 1.080e+02 6.200e+01 2.400e+01 0.000e+00 2.600e+01 2.230e-01
  2.500e+01 0.000e+00]
 [0.000e+00 1.810e+02 8.800e+01 4.400e+01 5.100e+02 4.330e+01 2.220e-01
  2.600e+01 1.000e+00]
 [8.000e+00 1.540e+02 7.800e+01 3.200e+01 0.000e+00 3.240e+01 4.430e-01
  4.500e+01 1.000e+00]
 [1.000e+00 1.280e+02 8.800e+01 3.900e+01 1.100e+02 3.650e+01 1.057e+00
  3.700e+01 1.000e+00]
 [7.000e+00 1.370e+02 9.000e+01 4.100e+01 0.000e+00 3.200e+01 3.910e-01
  3.900e+01 0.000e+00]
 [0.000e+00 1.230e+02 7.200e+01 0.000e+00 0.000e+00 3.630e

### Pré-processamento de Dados

In [12]:
import numpy as np 
from sklearn import preprocessing

atributos_normalizados = min_max.transform(base_Testes[:,:8])
print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
print(atributos_normalizados)


--------------------------------
Atributos de Entrada - Numéricos
--------------------------------
[[0.17647059 0.93969849 0.57377049 0.22222222 0.23640662 0.54247392
  0.14090521 0.25      ]
 [0.35294118 0.81407035 0.50819672 0.         0.         0.36214605
  0.04269855 0.48333333]
 [0.23529412 0.68341709 0.57377049 0.         0.         0.46497765
  0.47139197 0.01666667]
 [0.05882353 0.6080402  0.63934426 0.39393939 0.08747045 0.58122206
  0.07813834 0.11666667]
 [0.17647059 0.54271357 0.50819672 0.24242424 0.         0.38748137
  0.06191289 0.06666667]
 [0.         0.90954774 0.72131148 0.44444444 0.60283688 0.64530551
  0.06148591 0.08333333]
 [0.47058824 0.77386935 0.63934426 0.32323232 0.         0.4828614
  0.1558497  0.4       ]
 [0.05882353 0.64321608 0.72131148 0.39393939 0.13002364 0.54396423
  0.41801879 0.26666667]
 [0.41176471 0.68844221 0.73770492 0.41414141 0.         0.47690015
  0.13364646 0.3       ]
 [0.         0.61809045 0.59016393 0.         0.         0.540983

### Predição da Base

In [13]:
base_Predicao = modelo.predict((atributos_normalizados))
print("Classificações: ", base_Predicao)

Classificações:  [0. 0. 1. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0.]
